name: transen_payment
description: Payment and Wallet module for TranSen.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  transen_core:
    path: ../../core
  transen_auth:
    path: ../auth
  transen_trips:
    path: ../trips
  cloud_firestore: ^6.2.0
  flutter_riverpod: ^3.3.1
  url_launcher: ^6.1.11
  http: ^1.2.1
  dio: ^5.4.1
  share_plus: ^13.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
