// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_rQGC9og_n-mNYKQ8pd8M0_j6GWfM-JM',
    appId: '1:743590908369:web:cf0175ea723116d55cd0f0',
    messagingSenderId: '743590908369',
    projectId: 'allo-dakar-b6a20',
    authDomain: 'allo-dakar-b6a20.firebaseapp.com',
    storageBucket: 'allo-dakar-b6a20.firebasestorage.app',
    measurementId: 'G-WDR484QG4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgKZdHj-qCf9o8KBeEMzZwMFtOqwbeYaU',
    appId: '1:743590908369:android:cd3fd414ced552195cd0f0',
    messagingSenderId: '743590908369',
    projectId: 'allo-dakar-b6a20',
    storageBucket: 'allo-dakar-b6a20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzVsYHhMYHEtLOpxRphtZu1hF25BmkEo',
    appId: '1:743590908369:ios:2a1e5bef86b5bf805cd0f0',
    messagingSenderId: '743590908369',
    projectId: 'allo-dakar-b6a20',
    storageBucket: 'allo-dakar-b6a20.firebasestorage.app',
    iosBundleId: 'com.example.alloDakar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDzVsYHhMYHEtLOpxRphtZu1hF25BmkEo',
    appId: '1:743590908369:ios:2a1e5bef86b5bf805cd0f0',
    messagingSenderId: '743590908369',
    projectId: 'allo-dakar-b6a20',
    storageBucket: 'allo-dakar-b6a20.firebasestorage.app',
    iosBundleId: 'com.example.alloDakar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_rQGC9og_n-mNYKQ8pd8M0_j6GWfM-JM',
    appId: '1:743590908369:web:c9217fa181e417815cd0f0',
    messagingSenderId: '743590908369',
    projectId: 'allo-dakar-b6a20',
    authDomain: 'allo-dakar-b6a20.firebaseapp.com',
    storageBucket: 'allo-dakar-b6a20.firebasestorage.app',
    measurementId: 'G-95CNKT9V19',
  );
}
