name: transen_profile
description: Profile and Settings module for TranSen.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  transen_core:
    path: ../../core
  transen_auth:
    path: ../auth
  cloud_firestore: ^6.2.0
  flutter_riverpod: ^3.3.1
  share_plus: ^13.1.0
  url_launcher: ^6.1.11
  transen_trips:
    path: ../trips

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
