/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zsnxuwfawymeeqtqeiyr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzbnh1d2Zhd3ltZWVxdHFlaXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMjY2MjAsImV4cCI6MjA3ODcwMjYyMH0.VlU5pcMJygX2qhrxPnG-C99W-5lCeX1P15evo9Enomc"